//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardeHareAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocId { get; set; }
        public string TableName { get; set; }
        public int TableId { get; set; }
        public string DocName { get; set; }
        public string DocPath { get; set; }
        public string DocType { get; set; }
        public byte UserId { get; set; }
        public byte Active { get; set; }
        public System.DateTime Updt_Time { get; set; }
    }
}
