//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardeHareAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packing
    {
        public int PackId { get; set; }
        public int TagDetId { get; set; }
        public string Packer { get; set; }
        public string Addressee { get; set; }
        public string Packing1 { get; set; }
        public string ContainerDetail { get; set; }
        public string Weight { get; set; }
        public string ShippingLine { get; set; }
        public string Vessel { get; set; }
        public string BookingRef { get; set; }
        public string VoyNo { get; set; }
        public string ReleaseNo { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string EmptyDepot { get; set; }
        public string PortOfLoading { get; set; }
        public string PortOfTranshipment { get; set; }
        public string FinalDestination { get; set; }
        public string OtherRequirement { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> ShippedQty { get; set; }
        public Nullable<decimal> AdjQty { get; set; }
        public Nullable<decimal> FXRate { get; set; }
        public Nullable<decimal> Brokerage_USD { get; set; }
        public Nullable<decimal> BankExp_USD { get; set; }
        public Nullable<decimal> DoxExp_USD { get; set; }
        public Nullable<decimal> Freight_USD { get; set; }
        public Nullable<decimal> Freight_AUD { get; set; }
        public string OtherRequirement1 { get; set; }
        public string OtherRequirement2 { get; set; }
        public string OtherRequirement3 { get; set; }
        public string OtherRequirement4 { get; set; }
        public string OtherRequirement5 { get; set; }
        public Nullable<decimal> Packing_AUD { get; set; }
        public string RFP { get; set; }
        public string EDN { get; set; }
        public string CommoditySpec { get; set; }
        public string Exporter { get; set; }
        public Nullable<decimal> ActFreight_AUD { get; set; }
        public Nullable<decimal> ActFreight_USD { get; set; }
        public byte Active { get; set; }
        public System.DateTime Updt_Time { get; set; }
    }
}
