//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardeHareAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurId { get; set; }
        public string ContractNo { get; set; }
        public System.DateTime ContractDate { get; set; }
        public string ContractType { get; set; }
        public int SupplierId { get; set; }
        public string Commodity { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
        public byte HAContract { get; set; }
        public decimal HAQuantity { get; set; }
        public string Quality { get; set; }
        public decimal Price { get; set; }
        public string Currency { get; set; }
        public string DeliveryLocation { get; set; }
        public System.DateTime DeliveryPeriod { get; set; }
        public string Packing { get; set; }
        public string PortOfLoading { get; set; }
        public string PaymentTerms { get; set; }
        public string Season { get; set; }
        public string TradeRules { get; set; }
        public string Broker { get; set; }
        public string BrokerContact { get; set; }
        public string SpecialCondition { get; set; }
        public string Representative { get; set; }
        public string RepresentativePhone { get; set; }
        public string RepresentativeEmail { get; set; }
        public string SellerContact { get; set; }
        public string SellerContactPhone { get; set; }
        public string SellerContactFax { get; set; }
        public string SellerContactEmail { get; set; }
        public string SellerBank { get; set; }
        public string SellerBankABN { get; set; }
        public string SellerBankBSB { get; set; }
        public string SellerBankAccountNo { get; set; }
        public string SellerBankAccountName { get; set; }
        public string SellerContractNo { get; set; }
        public byte Active { get; set; }
        public System.DateTime Updt_Time { get; set; }
    }
}
