//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardeHareAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleId { get; set; }
        public string ContractNo { get; set; }
        public System.DateTime ContractDate { get; set; }
        public string ContractType { get; set; }
        public int BuyerId { get; set; }
        public Nullable<int> NotifyPartyId { get; set; }
        public string Commodity { get; set; }
        public string CommoditySpec { get; set; }
        public decimal Quantity { get; set; }
        public string QuantitySpec { get; set; }
        public string Unit { get; set; }
        public byte HAContract { get; set; }
        public decimal HAQuantity { get; set; }
        public string Quality { get; set; }
        public decimal Price { get; set; }
        public string PriceSpec { get; set; }
        public string Origin { get; set; }
        public string Currency { get; set; }
        public string DeliveryLocation { get; set; }
        public System.DateTime Shipment { get; set; }
        public string ShipmentSpec { get; set; }
        public string Packing { get; set; }
        public string PortOfDischarge { get; set; }
        public string PaymentTerms { get; set; }
        public string Broker { get; set; }
        public string BrokerContact { get; set; }
        public string Representative { get; set; }
        public string BuyerBank { get; set; }
        public string AQIS { get; set; }
        public string Fumigation { get; set; }
        public string TradeRules { get; set; }
        public string SpecialCondition { get; set; }
        public byte Active { get; set; }
        public System.DateTime Updt_Time { get; set; }
    }
}
