//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardeHareAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagDetail
    {
        public int TagDetId { get; set; }
        public int TagId { get; set; }
        public int PurId { get; set; }
        public int SaleId { get; set; }
        public decimal TagQuantity { get; set; }
        public byte Active { get; set; }
        public System.DateTime Updt_Time { get; set; }
    }
}
