//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardeHareAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuth
    {
        public int UserLoginId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.DateTime> Updt_Time { get; set; }
    }
}
