//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardeHareAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvwLastSellerDetail
    {
        public int SupplierId { get; set; }
        public string Broker { get; set; }
        public string BrokerContact { get; set; }
        public string SellerContact { get; set; }
        public string SellerContactPhone { get; set; }
        public string SellerContactFax { get; set; }
        public string SellerContactEmail { get; set; }
        public string SellerBank { get; set; }
        public string SellerBankABN { get; set; }
        public string SellerBankBSB { get; set; }
        public string SellerBankAccountNo { get; set; }
        public string SellerBankAccountName { get; set; }
    }
}
