//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TardeHareAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvwLastPurchaseDetail
    {
        public string Commodity { get; set; }
        public Nullable<int> Quantitiy { get; set; }
        public string Unit { get; set; }
        public string Quality { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> DeliveryPeriod { get; set; }
        public string Packing { get; set; }
        public string PaymentTerms { get; set; }
        public string TradeRules { get; set; }
    }
}
